[loggers]
keys = root, uvicorn, uvicorn_error, uvicorn_access, app

[logger_root]
level = INFO
handlers = handler_root

[logger_uvicorn]
level = INFO
handlers = handler_uvicorn_error, handler_uvicorn_access
qualname = uvicorn
propagate = 0

[logger_uvicorn_error]
level = INFO
handlers = handler_uvicorn_error
qualname = uvicorn.error
propagate = 0

[logger_uvicorn_access]
level = INFO
handlers = handler_uvicorn_access
qualname = uvicorn.access
propagate = 0

[logger_app]
level = INFO
handlers = handler_root
qualname = app
propagate = 0

[handlers]
keys = handler_root, handler_uvicorn_error, handler_uvicorn_access

[handler_handler_root]
class = logging.StreamHandler
level = NOTSET
formatter = fmt_main
args = ()

[handler_handler_uvicorn_error]
class = logging.StreamHandler
level = NOTSET
formatter = fmt_uvicorn_error
args = ()

[handler_handler_uvicorn_access]
class = logging.StreamHandler
level = NOTSET
formatter = fmt_uvicorn_access
args = ()

[formatters]
keys = fmt_main, fmt_uvicorn_error, fmt_uvicorn_access

[formatter_fmt_main]
format = %(asctime)s | %(levelname)-7s | %(name)s | %(message)s
datefmt = %H:%M:%S

[formatter_fmt_uvicorn_error]
format = %(asctime)s | %(levelname)-7s | uvicorn.error | %(message)s
datefmt = %H:%M:%S

[formatter_fmt_uvicorn_access]
format = %(asctime)s | %(message)s
datefmt = %H:%M:%S
