[loggers]
keys = root, uvicorn, uvicorn_error, uvicorn_access, app

[logger_root]
level = INFO
handlers = handler_root

[logger_uvicorn]
level = INFO
handlers = handler_root
qualname = uvicorn
propagate = 0

[logger_uvicorn_error]
level = INFO
handlers = handler_root
qualname = uvicorn.error
propagate = 0

[logger_uvicorn_access]
level = INFO
handlers = handler_root
qualname = uvicorn.access
propagate = 0

[logger_app]
level = INFO
handlers = handler_root
qualname = app
propagate = 0

[handlers]
keys = handler_root

[handler_handler_root]
class = logging.StreamHandler
level = NOTSET
formatter = fmt_main
args = ()

[formatters]
keys = fmt_main

[formatter_fmt_main]
format = %(asctime)s | %(levelname)-7s | %(name)s | %(message)s
datefmt = %H:%M:%S
